[build]
publish = "public"
command = """\
  npm install && \
  curl -LJO https://github.com/sass/dart-sass/releases/download/1.63.6/dart-sass-1.63.6-linux-x64.tar.gz && \
  tar -xf dart-sass-1.63.6-linux-x64.tar.gz && \
  rm dart-sass-1.63.6-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify
"""

[context.production.environment]
HUGO_VERSION = "0.139.4"
HUGO_EXTENDED = "true"
